[workspace]
resolver = "2"

members = [ "cli", "frontend", "server", "shared", "tests" ]

[workspace.dependencies]
anyhow = "1.0"
serde = "1.0"
tokio = "1.46"
url = "2.5"
reqwest = "0.13"
object_store = "0.13"
