[package]
name = "shared"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true, features = ["derive"] }
url = { workspace = true, features = ["serde"] }
hmac-sha256 = "1.1.12"
tinyrand = "0.5.0"
reqwest = { workspace = true, features = ["json"] }
thiserror = "2.0.18"
