name: test

on: [workflow_call]

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
        with:
          persist-credentials: false
      - uses: CfirTsabari/actions-rs-toolchain@fcebefd2149855a4b12c9ee62208ed0f622de15b
      - run: cargo install wasm-bindgen-cli --version 0.2.108
      - uses: extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff
      - name: Run tests
        env:
          ITLKD_SERVER_PATH: target/debug/itlkd-server
          ITLKD_CLI_PATH: target/debug/itlkd
        run: just test
