name: test

on: [workflow_call]

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@f7ccc83f9ed1e5b9c81d8a67d7ad1a747e22a561
      - run: cargo install wasm-bindgen-cli --version 0.2.108
      - uses: extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff
      - run: just build
      - name: Run tests
        env:
          ITLKD_SERVER_PATH: target/debug/itlkd-server
          ITLKD_CLI_PATH: target/debug/itlkd
        run: cargo test -p tests
